[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fmt]
sort_imports = true
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
quote_style = "double"
tab_width = 4